In [22]:
from tensorflow.keras.preprocessing.text import one_hot

In [23]:
### sentences 
sent=['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good', ]


In [24]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
## Define the vocabulary size
voc_size=10000

In [35]:
## Onen hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4781, 5007, 2591, 5284],
 [4781, 5007, 2591, 2074],
 [4781, 9193, 2591, 4207],
 [2923, 4534, 3698, 6834, 2543],
 [2923, 4534, 3698, 6834, 352],
 [9182, 4781, 5943, 2591, 5949],
 [5730, 464, 2607, 6834]]

In [27]:
## word Embedding Representation 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
import numpy as np

In [29]:
sent_length = 8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 4781, 5007, 2591, 5284],
       [   0,    0,    0,    0, 4781, 5007, 2591, 2074],
       [   0,    0,    0,    0, 4781, 9193, 2591, 4207],
       [   0,    0,    0, 2923, 4534, 3698, 6834, 2543],
       [   0,    0,    0, 2923, 4534, 3698, 6834,  352],
       [   0,    0,    0, 9182, 4781, 5943, 2591, 5949],
       [   0,    0,    0,    0, 5730,  464, 2607, 6834]])

In [30]:
## feature representation 
dim=10

In [39]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\set-ups\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [40]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step


array([[[ 0.03111425, -0.03036888, -0.03705097,  0.02436231,
         -0.02579285, -0.04689931, -0.00610654,  0.04068465,
          0.04225509,  0.04122261],
        [ 0.03111425, -0.03036888, -0.03705097,  0.02436231,
         -0.02579285, -0.04689931, -0.00610654,  0.04068465,
          0.04225509,  0.04122261],
        [ 0.03111425, -0.03036888, -0.03705097,  0.02436231,
         -0.02579285, -0.04689931, -0.00610654,  0.04068465,
          0.04225509,  0.04122261],
        [ 0.03111425, -0.03036888, -0.03705097,  0.02436231,
         -0.02579285, -0.04689931, -0.00610654,  0.04068465,
          0.04225509,  0.04122261],
        [ 0.02245632,  0.04525233, -0.01952633, -0.00890857,
          0.02108327, -0.02327999, -0.01710678,  0.04235157,
          0.0263036 ,  0.04514474],
        [ 0.00123569, -0.04479067, -0.02538379, -0.01704609,
          0.00048044, -0.03865372, -0.02326393, -0.04119456,
         -0.01396231,  0.03929153],
        [ 0.01710898, -0.01861625,  0.02874643,  0.0

In [42]:
embedded_docs[0]

array([   0,    0,    0,    0, 4781, 5007, 2591, 5284])